version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: on-failure
    networks:
      - lan
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: admin

networks:
  lan: